name: End-to-end tests
on: push
jobs:
  install:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Cypress install
          uses: cypress-io/github-action@v6
          with:
            # Disable running of tests within install job
            runTests: false
            build: npm run build

        - name: Save .next folder
          uses: actions/upload-artifact@v4
          with:
            name: next-artifact
            if-no-files-found: error
            path: .next

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the .next folder
        uses: actions/download-artifact@v4
        with:
          name: next-artifact
          path: .next

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          browser: chrome
          record: true
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}